    #include<stdio.h>
    #include<string.h>
    char arr[102];
    int main()
    {
    	int t,i,chef,frnd,flag,cc,cf;
    	scanf("%d\n",&t);
    	while(t--)
    	{
    		chef=0;
    		frnd=0;
    		flag=0;
    		cc=0;
    		cf=0;
    		scanf("%s",arr);
    		for(i=0;i<strlen(arr);i++)
    		{
    			if(arr[i]=='0')
    				frnd++;
    			if(arr[i]=='1')
    				chef++;
    			if(chef>=11){
    				printf("WIN\n");
    				flag=1;
    				break;
    			}
    			if(frnd>=11)
    			{
    				printf("LOSE\n");
    				flag=1;
    				break;
    			}
    			if(chef==10&&frnd==10)
                    break;
    		}
    		if(flag==0){
                    i++;
    		for(;i<strlen(arr);i++){
    			if(arr[i]=='1')
    				cc++;
    			else
    				cf++;
    			if((cc-cf)==2)
    			{
    				printf("WIN\n");
    				break;
    			}
    			else
    			if((cf-cc)==2)
    			{
    				printf("LOSE\n");
    				break;
    			}
    		}
    		}
    	}
    	return 0;
    }
